# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/tranqu.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'v1/tranqu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fv1/tranqu.proto\x12\x16tranqu_server.proto.v1\"\xa4\x01\n\x10TranspileRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07program\x18\x02 \x01(\t\x12\x13\n\x0bprogram_lib\x18\x03 \x01(\t\x12\x16\n\x0etranspiler_lib\x18\x04 \x01(\t\x12\x1a\n\x12transpiler_options\x18\x05 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x06 \x01(\t\x12\x12\n\ndevice_lib\x18\x07 \x01(\t\"\x81\x01\n\x11TranspileResponse\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x1a\n\x12transpiled_program\x18\x02 \x01(\t\x12\r\n\x05stats\x18\x03 \x01(\t\x12 \n\x18virtual_physical_mapping\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t2w\n\x11TranspilerService\x12\x62\n\tTranspile\x12(.tranqu_server.proto.v1.TranspileRequest\x1a).tranqu_server.proto.v1.TranspileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.tranqu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSPILEREQUEST']._serialized_start=44
  _globals['_TRANSPILEREQUEST']._serialized_end=208
  _globals['_TRANSPILERESPONSE']._serialized_start=211
  _globals['_TRANSPILERESPONSE']._serialized_end=340
  _globals['_TRANSPILERSERVICE']._serialized_start=342
  _globals['_TRANSPILERSERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
